# Generated by Django 2.2.14 on 2020-08-15 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_note_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='post',
            new_name='note',
        ),
    ]
