# Generated by Django 2.2.14 on 2020-08-17 18:29

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200815_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image1',
            field=models.ImageField(default='', upload_to=catalog.models.get_image_filename, verbose_name='Image'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
