# Generated by Django 2.2.14 on 2020-08-17 19:02

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200817_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='image1',
            field=models.ImageField(upload_to=catalog.models.get_image_filename, verbose_name='Image'),
        ),
    ]
