# Generated by Django 2.2.14 on 2020-08-17 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_note_image1_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='image1_url',
        ),
    ]
