# Generated by Django 2.2.14 on 2020-08-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200817_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='image1',
            field=models.ImageField(upload_to='note_images', verbose_name='Image 1'),
        ),
    ]
