# Generated by Django 2.2.14 on 2020-08-17 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20200817_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'permissions': (('can_view_all_notes', 'Can View All Notes'),)},
        ),
    ]
